# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_events.proto',
  package='car_events',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x63\x61r_events.proto\x12\ncar_events\"\x13\n\x05\x43\x61rId\x12\n\n\x02id\x18\x01 \x02(\x05\"C\n\x08\x43\x61rEvent\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0b\n\x03lat\x18\x02 \x02(\x01\x12\x0b\n\x03lon\x18\x03 \x02(\x01\x12\x11\n\ttimestamp\x18\x04 \x02(\x05')
)




_CARID = _descriptor.Descriptor(
  name='CarId',
  full_name='car_events.CarId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='car_events.CarId.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=51,
)


_CAREVENT = _descriptor.Descriptor(
  name='CarEvent',
  full_name='car_events.CarEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='car_events.CarEvent.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='car_events.CarEvent.lat', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='car_events.CarEvent.lon', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='car_events.CarEvent.timestamp', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['CarId'] = _CARID
DESCRIPTOR.message_types_by_name['CarEvent'] = _CAREVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarId = _reflection.GeneratedProtocolMessageType('CarId', (_message.Message,), dict(
  DESCRIPTOR = _CARID,
  __module__ = 'car_events_pb2'
  # @@protoc_insertion_point(class_scope:car_events.CarId)
  ))
_sym_db.RegisterMessage(CarId)

CarEvent = _reflection.GeneratedProtocolMessageType('CarEvent', (_message.Message,), dict(
  DESCRIPTOR = _CAREVENT,
  __module__ = 'car_events_pb2'
  # @@protoc_insertion_point(class_scope:car_events.CarEvent)
  ))
_sym_db.RegisterMessage(CarEvent)


# @@protoc_insertion_point(module_scope)
